#version 460
#extension GL_EXT_buffer_reference2 : require
#extension GL_EXT_nonuniform_qualifier : require
#extension GL_KHR_shader_subgroup_ballot : require
layout(local_size_x = 64, local_size_y = 1, local_size_z = 1) in;

layout(set = 15, binding = 0, std430) restrict readonly buffer SSBO_Offsets
{
    uvec2 _m0[];
} _13;

layout(set = 1, binding = 0, std430) restrict readonly buffer SSBO
{
    uvec2 _m0[];
} _18[];

layout(set = 1, binding = 0, std430) restrict readonly buffer _21_24
{
    uvec4 _m0[];
} _24[];

layout(set = 4, binding = 0, std430) writeonly buffer _26_29
{
    uvec2 _m0[];
} _29[];

layout(set = 4, binding = 0, std430) writeonly buffer _31_34
{
    uvec4 _m0[];
} _34[];

layout(set = 4, binding = 0, std430) buffer _36_39
{
    uint _m0[];
} _39[];

layout(push_constant, std430) uniform RootConstants
{
    uint _m0;
    uint _m1;
    uint _m2;
    uint _m3;
    uint _m4;
    uint _m5;
    uint _m6;
    uint _m7;
    uint _m8;
    uint _m9;
    uint _m10;
    uint _m11;
    uint _m12;
    uint _m13;
    uint _m14;
    uint _m15;
} registers;

layout(set = 4, binding = 0) uniform writeonly uimageBuffer _43[];

uint ByteAddressMask(uint index, uint stride)
{
    return index & (4294967295u / stride);
}

void main()
{
    uint _55 = (subgroupBroadcastFirst(registers._m4) * 2u) + 1u;
    uvec2 _69 = _13._m0[subgroupBroadcastFirst(registers._m4) * 2u] >> uvec2(2u);
    uint _75 = registers._m4 + 1u;
    uvec2 _80 = _13._m0[subgroupBroadcastFirst(_75) * 2u] >> uvec2(4u);
    uvec2 _90 = _13._m0[subgroupBroadcastFirst(registers._m4) * 2u] >> uvec2(3u);
    uint _96 = registers._m1 + 1u;
    uvec2 _101 = _13._m0[subgroupBroadcastFirst(_96) * 2u] >> uvec2(4u);
    uvec2 _110 = _13._m0[subgroupBroadcastFirst(registers._m1) * 2u] >> uvec2(3u);
    vec2 _131 = uintBitsToFloat(_18[registers._m1]._m0[(gl_GlobalInvocationID.x < _110.y) ? (gl_GlobalInvocationID.x + _110.x) : 536870911u]);
    _29[registers._m4]._m0[(gl_GlobalInvocationID.x < _90.y) ? (gl_GlobalInvocationID.x + _90.x) : 536870911u] = uvec2(floatBitsToUint(_131.x), floatBitsToUint(_131.y));
    uint _153 = ByteAddressMask(gl_GlobalInvocationID.x, 16u);
    uint _168 = ByteAddressMask(gl_GlobalInvocationID.x, 16u);
    _34[_75]._m0[(_168 < _80.y) ? (_168 + _80.x) : 268435455u] = uvec4(_24[_96]._m0[(_153 < _101.y) ? (_153 + _101.x) : 268435455u]);
    vec2 _183 = uintBitsToFloat(_18[registers._m1]._m0[(gl_GlobalInvocationID.x < _110.y) ? (gl_GlobalInvocationID.x + _110.x) : 536870911u]);
    _29[registers._m4]._m0[(gl_GlobalInvocationID.x < _90.y) ? (gl_GlobalInvocationID.x + _90.x) : 536870911u] = uvec2(floatBitsToUint(_183.x), floatBitsToUint(_183.y));
    uint _195 = ByteAddressMask(gl_GlobalInvocationID.x, 16u);
    uint _207 = ByteAddressMask(gl_GlobalInvocationID.x, 16u);
    _34[_75]._m0[(_207 < _80.y) ? (_207 + _80.x) : 268435455u] = uvec4(_24[_96]._m0[(_195 < _101.y) ? (_195 + _101.x) : 268435455u]);
    uint _219 = registers._m1 + (gl_WorkGroupID.x + 2u);
    uvec2 _224 = _13._m0[subgroupBroadcastFirst(_219) * 2u] >> uvec2(3u);
    vec2 _232 = uintBitsToFloat(_18[_219]._m0[(gl_GlobalInvocationID.x < _224.y) ? (gl_GlobalInvocationID.x + _224.x) : 536870911u]);
    uint _239 = registers._m4 + (gl_WorkGroupID.x + 0u);
    uvec2 _244 = _13._m0[subgroupBroadcastFirst(_239) * 2u] >> uvec2(3u);
    _29[_239]._m0[(gl_GlobalInvocationID.x < _244.y) ? (gl_GlobalInvocationID.x + _244.x) : 536870911u] = uvec2(floatBitsToUint(_232.x), floatBitsToUint(_232.y));
    uint _258 = registers._m1 + (gl_GlobalInvocationID.x + 2u);
    uvec2 _262 = _13._m0[_258 * 2u] >> uvec2(3u);
    vec2 _270 = uintBitsToFloat(_18[nonuniformEXT(_258)]._m0[(gl_GlobalInvocationID.x < _262.y) ? (gl_GlobalInvocationID.x + _262.x) : 536870911u]);
    uint _277 = registers._m4 + (gl_GlobalInvocationID.x + 0u);
    uvec2 _281 = _13._m0[_277 * 2u] >> uvec2(3u);
    _29[nonuniformEXT(_277)]._m0[(gl_GlobalInvocationID.x < _281.y) ? (gl_GlobalInvocationID.x + _281.x) : 536870911u] = uvec2(floatBitsToUint(_270.x), floatBitsToUint(_270.y));
    uint _295 = registers._m1 + (gl_WorkGroupID.x + 3u);
    uvec2 _300 = _13._m0[subgroupBroadcastFirst(_295) * 2u] >> uvec2(4u);
    uint _301 = ByteAddressMask(gl_GlobalInvocationID.x, 16u);
    uint _317 = registers._m4 + (gl_WorkGroupID.x + 1u);
    uvec2 _322 = _13._m0[subgroupBroadcastFirst(_317) * 2u] >> uvec2(4u);
    uint _323 = ByteAddressMask(gl_GlobalInvocationID.x, 16u);
    _34[_317]._m0[(_323 < _322.y) ? (_323 + _322.x) : 268435455u] = uvec4(_24[_295]._m0[(_301 < _300.y) ? (_301 + _300.x) : 268435455u]);
    uint _335 = registers._m1 + (gl_GlobalInvocationID.x + 3u);
    uvec2 _339 = _13._m0[_335 * 2u] >> uvec2(4u);
    uint _340 = ByteAddressMask(gl_GlobalInvocationID.x, 16u);
    uint _356 = registers._m4 + (gl_GlobalInvocationID.x + 1u);
    uvec2 _360 = _13._m0[_356 * 2u] >> uvec2(4u);
    uint _361 = ByteAddressMask(gl_GlobalInvocationID.x, 16u);
    _34[nonuniformEXT(_356)]._m0[(_361 < _360.y) ? (_361 + _360.x) : 268435455u] = uvec4(_24[nonuniformEXT(_335)]._m0[(_340 < _339.y) ? (_340 + _339.x) : 268435455u]);
    uint _370 = (gl_GlobalInvocationID.x * 2u) + 1u;
    uint _379 = atomicAdd(_39[registers._m4]._m0[(_370 < _69.y) ? (_370 + _69.x) : 1073741820u], 1u);
    uint _382 = gl_GlobalInvocationID.x * 2u;
    uint _389 = atomicAdd(_39[registers._m4]._m0[(_382 < _69.y) ? (_382 + _69.x) : 1073741820u], _90.y / 1u);
    uint _390 = gl_GlobalInvocationID.x << 2u;
    imageStore(_43[registers._m4], int((gl_GlobalInvocationID.x < _13._m0[_55].y) ? (gl_GlobalInvocationID.x + _13._m0[_55].x) : 4294967295u), uvec4(_390, _390 | 1u, _390 | 2u, _390 | 3u));
}


#if 0
// SPIR-V disassembly
; SPIR-V
; Version: 1.3
; Generator: Unknown(30017); 21022
; Bound: 402
; Schema: 0
OpCapability Shader
OpCapability StorageBufferArrayDynamicIndexing
OpCapability ImageBuffer
OpCapability ImageQuery
OpCapability StorageImageWriteWithoutFormat
OpCapability GroupNonUniformBallot
OpCapability RuntimeDescriptorArray
OpCapability StorageBufferArrayNonUniformIndexing
OpCapability PhysicalStorageBufferAddresses
OpExtension "SPV_EXT_descriptor_indexing"
OpExtension "SPV_KHR_physical_storage_buffer"
OpMemoryModel PhysicalStorageBuffer64 GLSL450
OpEntryPoint GLCompute %3 "main" %113 %117
OpExecutionMode %3 LocalSize 64 1 1
OpName %3 "main"
OpName %6 "RootConstants"
OpName %8 "registers"
OpName %11 "SSBO_Offsets"
OpName %15 "SSBO"
OpName %21 "SSBO"
OpName %26 "SSBO"
OpName %31 "SSBO"
OpName %36 "SSBO"
OpName %147 "ByteAddressMask"
OpName %145 "index"
OpName %146 "stride"
OpDecorate %6 Block
OpMemberDecorate %6 0 Offset 0
OpMemberDecorate %6 1 Offset 4
OpMemberDecorate %6 2 Offset 8
OpMemberDecorate %6 3 Offset 12
OpMemberDecorate %6 4 Offset 16
OpMemberDecorate %6 5 Offset 20
OpMemberDecorate %6 6 Offset 24
OpMemberDecorate %6 7 Offset 28
OpMemberDecorate %6 8 Offset 32
OpMemberDecorate %6 9 Offset 36
OpMemberDecorate %6 10 Offset 40
OpMemberDecorate %6 11 Offset 44
OpMemberDecorate %6 12 Offset 48
OpMemberDecorate %6 13 Offset 52
OpMemberDecorate %6 14 Offset 56
OpMemberDecorate %6 15 Offset 60
OpDecorate %10 ArrayStride 8
OpMemberDecorate %11 0 Offset 0
OpDecorate %11 Block
OpDecorate %13 DescriptorSet 15
OpDecorate %13 Binding 0
OpDecorate %13 NonWritable
OpDecorate %13 Restrict
OpDecorate %14 ArrayStride 8
OpMemberDecorate %15 0 Offset 0
OpDecorate %15 Block
OpDecorate %18 DescriptorSet 1
OpDecorate %18 Binding 0
OpDecorate %18 NonWritable
OpDecorate %18 Restrict
OpDecorate %20 ArrayStride 16
OpMemberDecorate %21 0 Offset 0
OpDecorate %21 Block
OpDecorate %24 DescriptorSet 1
OpDecorate %24 Binding 0
OpDecorate %24 NonWritable
OpDecorate %24 Restrict
OpDecorate %25 ArrayStride 8
OpMemberDecorate %26 0 Offset 0
OpDecorate %26 Block
OpDecorate %29 DescriptorSet 4
OpDecorate %29 Binding 0
OpDecorate %29 NonReadable
OpDecorate %30 ArrayStride 16
OpMemberDecorate %31 0 Offset 0
OpDecorate %31 Block
OpDecorate %34 DescriptorSet 4
OpDecorate %34 Binding 0
OpDecorate %34 NonReadable
OpDecorate %35 ArrayStride 4
OpMemberDecorate %36 0 Offset 0
OpDecorate %36 Block
OpDecorate %39 DescriptorSet 4
OpDecorate %39 Binding 0
OpDecorate %43 DescriptorSet 4
OpDecorate %43 Binding 0
OpDecorate %43 NonReadable
OpDecorate %113 BuiltIn GlobalInvocationId
OpDecorate %117 BuiltIn WorkgroupId
OpDecorate %258 NonUniform
OpDecorate %255 NonUniform
OpDecorate %268 NonUniform
OpDecorate %277 NonUniform
OpDecorate %274 NonUniform
OpDecorate %290 NonUniform
OpDecorate %335 NonUniform
OpDecorate %332 NonUniform
OpDecorate %346 NonUniform
OpDecorate %356 NonUniform
OpDecorate %353 NonUniform
OpDecorate %368 NonUniform
%1 = OpTypeVoid
%2 = OpTypeFunction %1
%5 = OpTypeInt 32 0
%6 = OpTypeStruct %5 %5 %5 %5 %5 %5 %5 %5 %5 %5 %5 %5 %5 %5 %5 %5
%7 = OpTypePointer PushConstant %6
%8 = OpVariable %7 PushConstant
%9 = OpTypeVector %5 2
%10 = OpTypeRuntimeArray %9
%11 = OpTypeStruct %10
%12 = OpTypePointer StorageBuffer %11
%13 = OpVariable %12 StorageBuffer
%14 = OpTypeRuntimeArray %9
%15 = OpTypeStruct %14
%16 = OpTypeRuntimeArray %15
%17 = OpTypePointer StorageBuffer %16
%18 = OpVariable %17 StorageBuffer
%19 = OpTypeVector %5 4
%20 = OpTypeRuntimeArray %19
%21 = OpTypeStruct %20
%22 = OpTypeRuntimeArray %21
%23 = OpTypePointer StorageBuffer %22
%24 = OpVariable %23 StorageBuffer
%25 = OpTypeRuntimeArray %9
%26 = OpTypeStruct %25
%27 = OpTypeRuntimeArray %26
%28 = OpTypePointer StorageBuffer %27
%29 = OpVariable %28 StorageBuffer
%30 = OpTypeRuntimeArray %19
%31 = OpTypeStruct %30
%32 = OpTypeRuntimeArray %31
%33 = OpTypePointer StorageBuffer %32
%34 = OpVariable %33 StorageBuffer
%35 = OpTypeRuntimeArray %5
%36 = OpTypeStruct %35
%37 = OpTypeRuntimeArray %36
%38 = OpTypePointer StorageBuffer %37
%39 = OpVariable %38 StorageBuffer
%40 = OpTypeImage %5 Buffer 0 0 0 2 Unknown
%41 = OpTypeRuntimeArray %40
%42 = OpTypePointer UniformConstant %41
%43 = OpVariable %42 UniformConstant
%44 = OpTypePointer UniformConstant %40
%46 = OpTypePointer PushConstant %5
%48 = OpConstant %5 4
%52 = OpConstant %5 3
%54 = OpConstant %5 2
%56 = OpConstant %5 1
%57 = OpTypePointer StorageBuffer %9
%59 = OpConstant %5 0
%61 = OpTypePointer StorageBuffer %36
%70 = OpConstantComposite %9 %54 %54
%71 = OpTypePointer StorageBuffer %31
%81 = OpConstantComposite %9 %48 %48
%82 = OpTypePointer StorageBuffer %26
%91 = OpConstantComposite %9 %52 %52
%92 = OpTypePointer StorageBuffer %21
%102 = OpTypePointer StorageBuffer %15
%111 = OpTypeVector %5 3
%112 = OpTypePointer Input %111
%113 = OpVariable %112 Input
%114 = OpTypePointer Input %5
%117 = OpVariable %112 Input
%123 = OpTypeBool
%126 = OpConstant %5 536870911
%129 = OpTypeFloat 32
%130 = OpTypeVector %129 2
%144 = OpTypeFunction %5 %5 %5
%150 = OpConstant %5 4294967295
%154 = OpConstant %5 16
%160 = OpConstant %5 268435455
%161 = OpTypePointer StorageBuffer %19
%376 = OpConstant %5 1073741820
%377 = OpTypePointer StorageBuffer %5
%3 = OpFunction %1 None %2
%4 = OpLabel
OpBranch %400
%400 = OpLabel
%47 = OpAccessChain %46 %8 %48
%49 = OpLoad %5 %47
%45 = OpAccessChain %44 %43 %49
%50 = OpLoad %40 %45
%51 = OpGroupNonUniformBroadcastFirst %5 %52 %49
%53 = OpIMul %5 %51 %54
%55 = OpIAdd %5 %53 %56
%58 = OpAccessChain %57 %13 %59 %55
%60 = OpLoad %9 %58
%63 = OpAccessChain %46 %8 %48
%64 = OpLoad %5 %63
%62 = OpAccessChain %61 %39 %64
%65 = OpGroupNonUniformBroadcastFirst %5 %52 %64
%66 = OpIMul %5 %65 %54
%67 = OpAccessChain %57 %13 %59 %66
%68 = OpLoad %9 %67
%69 = OpShiftRightLogical %9 %68 %70
%73 = OpAccessChain %46 %8 %48
%74 = OpLoad %5 %73
%75 = OpIAdd %5 %74 %56
%72 = OpAccessChain %71 %34 %75
%76 = OpGroupNonUniformBroadcastFirst %5 %52 %75
%77 = OpIMul %5 %76 %54
%78 = OpAccessChain %57 %13 %59 %77
%79 = OpLoad %9 %78
%80 = OpShiftRightLogical %9 %79 %81
%84 = OpAccessChain %46 %8 %48
%85 = OpLoad %5 %84
%83 = OpAccessChain %82 %29 %85
%86 = OpGroupNonUniformBroadcastFirst %5 %52 %85
%87 = OpIMul %5 %86 %54
%88 = OpAccessChain %57 %13 %59 %87
%89 = OpLoad %9 %88
%90 = OpShiftRightLogical %9 %89 %91
%94 = OpAccessChain %46 %8 %56
%95 = OpLoad %5 %94
%96 = OpIAdd %5 %95 %56
%93 = OpAccessChain %92 %24 %96
%97 = OpGroupNonUniformBroadcastFirst %5 %52 %96
%98 = OpIMul %5 %97 %54
%99 = OpAccessChain %57 %13 %59 %98
%100 = OpLoad %9 %99
%101 = OpShiftRightLogical %9 %100 %81
%104 = OpAccessChain %46 %8 %56
%105 = OpLoad %5 %104
%103 = OpAccessChain %102 %18 %105
%106 = OpGroupNonUniformBroadcastFirst %5 %52 %105
%107 = OpIMul %5 %106 %54
%108 = OpAccessChain %57 %13 %59 %107
%109 = OpLoad %9 %108
%110 = OpShiftRightLogical %9 %109 %91
%115 = OpAccessChain %114 %113 %59
%116 = OpLoad %5 %115
%118 = OpAccessChain %114 %117 %59
%119 = OpLoad %5 %118
%120 = OpCompositeExtract %5 %110 0
%121 = OpCompositeExtract %5 %110 1
%122 = OpIAdd %5 %116 %120
%124 = OpULessThan %123 %116 %121
%125 = OpSelect %5 %124 %122 %126
%127 = OpAccessChain %57 %103 %59 %125
%128 = OpLoad %9 %127
%131 = OpBitcast %130 %128
%132 = OpCompositeExtract %129 %131 0
%133 = OpCompositeExtract %129 %131 1
%134 = OpCompositeExtract %5 %90 0
%135 = OpCompositeExtract %5 %90 1
%136 = OpIAdd %5 %116 %134
%137 = OpULessThan %123 %116 %135
%138 = OpSelect %5 %137 %136 %126
%139 = OpBitcast %5 %132
%140 = OpBitcast %5 %133
%141 = OpCompositeConstruct %9 %139 %140
%142 = OpAccessChain %57 %83 %59 %138
OpStore %142 %141
%143 = OpShiftLeftLogical %5 %116 %48
%153 = OpFunctionCall %5 %147 %116 %154
%155 = OpCompositeExtract %5 %101 0
%156 = OpCompositeExtract %5 %101 1
%157 = OpIAdd %5 %153 %155
%158 = OpULessThan %123 %153 %156
%159 = OpSelect %5 %158 %157 %160
%162 = OpAccessChain %161 %93 %59 %159
%163 = OpLoad %19 %162
%164 = OpCompositeExtract %5 %163 0
%165 = OpCompositeExtract %5 %163 1
%166 = OpCompositeExtract %5 %163 2
%167 = OpCompositeExtract %5 %163 3
%168 = OpFunctionCall %5 %147 %116 %154
%169 = OpCompositeExtract %5 %80 0
%170 = OpCompositeExtract %5 %80 1
%171 = OpIAdd %5 %168 %169
%172 = OpULessThan %123 %168 %170
%173 = OpSelect %5 %172 %171 %160
%174 = OpCompositeConstruct %19 %164 %165 %166 %167
%175 = OpAccessChain %161 %72 %59 %173
OpStore %175 %174
%176 = OpCompositeExtract %5 %110 0
%177 = OpCompositeExtract %5 %110 1
%178 = OpIAdd %5 %116 %176
%179 = OpULessThan %123 %116 %177
%180 = OpSelect %5 %179 %178 %126
%181 = OpAccessChain %57 %103 %59 %180
%182 = OpLoad %9 %181
%183 = OpBitcast %130 %182
%184 = OpCompositeExtract %129 %183 0
%185 = OpCompositeExtract %129 %183 1
%186 = OpCompositeExtract %5 %90 0
%187 = OpCompositeExtract %5 %90 1
%188 = OpIAdd %5 %116 %186
%189 = OpULessThan %123 %116 %187
%190 = OpSelect %5 %189 %188 %126
%191 = OpBitcast %5 %184
%192 = OpBitcast %5 %185
%193 = OpCompositeConstruct %9 %191 %192
%194 = OpAccessChain %57 %83 %59 %190
OpStore %194 %193
%195 = OpFunctionCall %5 %147 %116 %154
%196 = OpCompositeExtract %5 %101 0
%197 = OpCompositeExtract %5 %101 1
%198 = OpIAdd %5 %195 %196
%199 = OpULessThan %123 %195 %197
%200 = OpSelect %5 %199 %198 %160
%201 = OpAccessChain %161 %93 %59 %200
%202 = OpLoad %19 %201
%203 = OpCompositeExtract %5 %202 0
%204 = OpCompositeExtract %5 %202 1
%205 = OpCompositeExtract %5 %202 2
%206 = OpCompositeExtract %5 %202 3
%207 = OpFunctionCall %5 %147 %116 %154
%208 = OpCompositeExtract %5 %80 0
%209 = OpCompositeExtract %5 %80 1
%210 = OpIAdd %5 %207 %208
%211 = OpULessThan %123 %207 %209
%212 = OpSelect %5 %211 %210 %160
%213 = OpCompositeConstruct %19 %203 %204 %205 %206
%214 = OpAccessChain %161 %72 %59 %212
OpStore %214 %213
%215 = OpIAdd %5 %119 %54
%217 = OpAccessChain %46 %8 %56
%218 = OpLoad %5 %217
%219 = OpIAdd %5 %218 %215
%216 = OpAccessChain %102 %18 %219
%220 = OpGroupNonUniformBroadcastFirst %5 %52 %219
%221 = OpIMul %5 %220 %54
%222 = OpAccessChain %57 %13 %59 %221
%223 = OpLoad %9 %222
%224 = OpShiftRightLogical %9 %223 %91
%225 = OpCompositeExtract %5 %224 0
%226 = OpCompositeExtract %5 %224 1
%227 = OpIAdd %5 %116 %225
%228 = OpULessThan %123 %116 %226
%229 = OpSelect %5 %228 %227 %126
%230 = OpAccessChain %57 %216 %59 %229
%231 = OpLoad %9 %230
%232 = OpBitcast %130 %231
%233 = OpCompositeExtract %129 %232 0
%234 = OpCompositeExtract %129 %232 1
%235 = OpIAdd %5 %119 %59
%237 = OpAccessChain %46 %8 %48
%238 = OpLoad %5 %237
%239 = OpIAdd %5 %238 %235
%236 = OpAccessChain %82 %29 %239
%240 = OpGroupNonUniformBroadcastFirst %5 %52 %239
%241 = OpIMul %5 %240 %54
%242 = OpAccessChain %57 %13 %59 %241
%243 = OpLoad %9 %242
%244 = OpShiftRightLogical %9 %243 %91
%245 = OpCompositeExtract %5 %244 0
%246 = OpCompositeExtract %5 %244 1
%247 = OpIAdd %5 %116 %245
%248 = OpULessThan %123 %116 %246
%249 = OpSelect %5 %248 %247 %126
%250 = OpBitcast %5 %233
%251 = OpBitcast %5 %234
%252 = OpCompositeConstruct %9 %250 %251
%253 = OpAccessChain %57 %236 %59 %249
OpStore %253 %252
%254 = OpIAdd %5 %116 %54
%256 = OpAccessChain %46 %8 %56
%257 = OpLoad %5 %256
%258 = OpIAdd %5 %257 %254
%255 = OpAccessChain %102 %18 %258
%259 = OpIMul %5 %258 %54
%260 = OpAccessChain %57 %13 %59 %259
%261 = OpLoad %9 %260
%262 = OpShiftRightLogical %9 %261 %91
%263 = OpCompositeExtract %5 %262 0
%264 = OpCompositeExtract %5 %262 1
%265 = OpIAdd %5 %116 %263
%266 = OpULessThan %123 %116 %264
%267 = OpSelect %5 %266 %265 %126
%268 = OpAccessChain %57 %255 %59 %267
%269 = OpLoad %9 %268
%270 = OpBitcast %130 %269
%271 = OpCompositeExtract %129 %270 0
%272 = OpCompositeExtract %129 %270 1
%273 = OpIAdd %5 %116 %59
%275 = OpAccessChain %46 %8 %48
%276 = OpLoad %5 %275
%277 = OpIAdd %5 %276 %273
%274 = OpAccessChain %82 %29 %277
%278 = OpIMul %5 %277 %54
%279 = OpAccessChain %57 %13 %59 %278
%280 = OpLoad %9 %279
%281 = OpShiftRightLogical %9 %280 %91
%282 = OpCompositeExtract %5 %281 0
%283 = OpCompositeExtract %5 %281 1
%284 = OpIAdd %5 %116 %282
%285 = OpULessThan %123 %116 %283
%286 = OpSelect %5 %285 %284 %126
%287 = OpBitcast %5 %271
%288 = OpBitcast %5 %272
%289 = OpCompositeConstruct %9 %287 %288
%290 = OpAccessChain %57 %274 %59 %286
OpStore %290 %289
%291 = OpIAdd %5 %119 %52
%293 = OpAccessChain %46 %8 %56
%294 = OpLoad %5 %293
%295 = OpIAdd %5 %294 %291
%292 = OpAccessChain %92 %24 %295
%296 = OpGroupNonUniformBroadcastFirst %5 %52 %295
%297 = OpIMul %5 %296 %54
%298 = OpAccessChain %57 %13 %59 %297
%299 = OpLoad %9 %298
%300 = OpShiftRightLogical %9 %299 %81
%301 = OpFunctionCall %5 %147 %116 %154
%302 = OpCompositeExtract %5 %300 0
%303 = OpCompositeExtract %5 %300 1
%304 = OpIAdd %5 %301 %302
%305 = OpULessThan %123 %301 %303
%306 = OpSelect %5 %305 %304 %160
%307 = OpAccessChain %161 %292 %59 %306
%308 = OpLoad %19 %307
%309 = OpCompositeExtract %5 %308 0
%310 = OpCompositeExtract %5 %308 1
%311 = OpCompositeExtract %5 %308 2
%312 = OpCompositeExtract %5 %308 3
%313 = OpIAdd %5 %119 %56
%315 = OpAccessChain %46 %8 %48
%316 = OpLoad %5 %315
%317 = OpIAdd %5 %316 %313
%314 = OpAccessChain %71 %34 %317
%318 = OpGroupNonUniformBroadcastFirst %5 %52 %317
%319 = OpIMul %5 %318 %54
%320 = OpAccessChain %57 %13 %59 %319
%321 = OpLoad %9 %320
%322 = OpShiftRightLogical %9 %321 %81
%323 = OpFunctionCall %5 %147 %116 %154
%324 = OpCompositeExtract %5 %322 0
%325 = OpCompositeExtract %5 %322 1
%326 = OpIAdd %5 %323 %324
%327 = OpULessThan %123 %323 %325
%328 = OpSelect %5 %327 %326 %160
%329 = OpCompositeConstruct %19 %309 %310 %311 %312
%330 = OpAccessChain %161 %314 %59 %328
OpStore %330 %329
%331 = OpIAdd %5 %116 %52
%333 = OpAccessChain %46 %8 %56
%334 = OpLoad %5 %333
%335 = OpIAdd %5 %334 %331
%332 = OpAccessChain %92 %24 %335
%336 = OpIMul %5 %335 %54
%337 = OpAccessChain %57 %13 %59 %336
%338 = OpLoad %9 %337
%339 = OpShiftRightLogical %9 %338 %81
%340 = OpFunctionCall %5 %147 %116 %154
%341 = OpCompositeExtract %5 %339 0
%342 = OpCompositeExtract %5 %339 1
%343 = OpIAdd %5 %340 %341
%344 = OpULessThan %123 %340 %342
%345 = OpSelect %5 %344 %343 %160
%346 = OpAccessChain %161 %332 %59 %345
%347 = OpLoad %19 %346
%348 = OpCompositeExtract %5 %347 0
%349 = OpCompositeExtract %5 %347 1
%350 = OpCompositeExtract %5 %347 2
%351 = OpCompositeExtract %5 %347 3
%352 = OpIAdd %5 %116 %56
%354 = OpAccessChain %46 %8 %48
%355 = OpLoad %5 %354
%356 = OpIAdd %5 %355 %352
%353 = OpAccessChain %71 %34 %356
%357 = OpIMul %5 %356 %54
%358 = OpAccessChain %57 %13 %59 %357
%359 = OpLoad %9 %358
%360 = OpShiftRightLogical %9 %359 %81
%361 = OpFunctionCall %5 %147 %116 %154
%362 = OpCompositeExtract %5 %360 0
%363 = OpCompositeExtract %5 %360 1
%364 = OpIAdd %5 %361 %362
%365 = OpULessThan %123 %361 %363
%366 = OpSelect %5 %365 %364 %160
%367 = OpCompositeConstruct %19 %348 %349 %350 %351
%368 = OpAccessChain %161 %353 %59 %366
OpStore %368 %367
%369 = OpIMul %5 %116 %54
%370 = OpIAdd %5 %369 %56
%371 = OpCompositeExtract %5 %69 0
%372 = OpCompositeExtract %5 %69 1
%373 = OpIAdd %5 %370 %371
%374 = OpULessThan %123 %370 %372
%375 = OpSelect %5 %374 %373 %376
%378 = OpAccessChain %377 %62 %59 %375
%379 = OpAtomicIAdd %5 %378 %56 %59 %56
%380 = OpCompositeExtract %5 %90 1
%381 = OpUDiv %5 %380 %56
%382 = OpIMul %5 %116 %54
%383 = OpCompositeExtract %5 %69 0
%384 = OpCompositeExtract %5 %69 1
%385 = OpIAdd %5 %382 %383
%386 = OpULessThan %123 %382 %384
%387 = OpSelect %5 %386 %385 %376
%388 = OpAccessChain %377 %62 %59 %387
%389 = OpAtomicIAdd %5 %388 %56 %59 %381
%390 = OpShiftLeftLogical %5 %116 %54
%391 = OpBitwiseOr %5 %390 %56
%392 = OpBitwiseOr %5 %390 %54
%393 = OpBitwiseOr %5 %390 %52
%394 = OpCompositeExtract %5 %60 0
%395 = OpCompositeExtract %5 %60 1
%396 = OpIAdd %5 %116 %394
%397 = OpULessThan %123 %116 %395
%398 = OpSelect %5 %397 %396 %150
%399 = OpCompositeConstruct %19 %390 %391 %392 %393
OpImageWrite %50 %398 %399
OpReturn
OpFunctionEnd
%147 = OpFunction %5 None %144
%145 = OpFunctionParameter %5
%146 = OpFunctionParameter %5
%148 = OpLabel
%149 = OpUDiv %5 %150 %146
%151 = OpBitwiseAnd %5 %145 %149
OpReturnValue %151
OpFunctionEnd
#endif
